salt: ${spring.profiles.active}
jasypt:
  encryptor:
    password: ${salt}
    bean: jasyptEncryptor
spring:
  application:
    name: corknote
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
      hibernate.dialect: org.hibernate.dialect.MariaDBDialect
tunneling:
  database:
    driver-class-name: org.mariadb.jdbc.Driver
    schema: ENC(F2weUiWiZogpbCxkxoMqLw==)
    port: ENC(xtseO2lbw8n5dcliYubR+A==)
    username: ENC(T5PICLFbq/P+JbeyVXnQGg==)
    password: ENC(catEbbfMNijPZHqSWRWD54B7cLM77KX1)
  ssh:
    host: ENC(+nWQqrJNLyu2UspL0tSwa3seNT30oD6sIQ7QlNgMO9w=)
    port: ENC(trUdZa6Ifhcv6CnLnctflw==)
    username: ENC(QPV2VP7wxYIVJL0lRQv80w==)
    password: ENC(al37M+z/7bPz0cJmqg15Lf5Vqxdzb69J)
logging:
  root: off
kologger:
  level: INFO # ALL, INFO, WARN, ERROR, OFF
  jdbc: true # true, false
  log-format:
    placeholder: "{datetime} [{thread}:{level}] - {msg}{new-line}"
    date-time-format: yyyy-MM-dd HH:mm:ss
  file-recode:
    directory: log/
    placeholder: YOUR_PROJECT_NAME{date}.log
    date-format: yyyy-MM-dd